name: ecommerce_ui_kit
description: Prime Ecommerce Flutter Ui Kit
#  A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# Dart 3.0.2
# Flutter 3.10.2
version: 1.0.1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  woocommerce_api: ^0.1.0
  cupertino_icons: ^1.0.2
  connectivity_plus: ^3.0.3
  fluttertoast: ^8.2.1
  flutter_svg: ^2.0.3
  pinput:
  get: ^4.6.5
  carousel_slider: ^4.2.1
  dots_indicator: ^2.1.0
  cached_network_image: ^3.2.3
  flutter_switch: ^0.3.2
  country_code_picker: ^3.0.0
  intl_phone_number_input: ^0.7.3+1
  country_state_picker: ^0.0.4
  csc_picker: ^0.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/onboarding/
    - assets/images/login/
    - assets/images/resetpassword/
    - assets/images/signin/
    - assets/images/home/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
        - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins/Poppins-ThinItalic.ttf
    - family: Noto_Serif_TC
      fonts:
        - asset: assets/fonts/Noto_Serif_TC/NotoSerifTC-Black.otf
    - family: BodaniMode_Italic
      fonts:
        - asset: assets/fonts/Bodoni_Moda/bodonimoda-italic.ttf


